# Generated by Django 6.1 on 2026-09-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_inventoryitem_usertool'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tipo',
            field=models.CharField(choices=[('eletronica', 'Eletrônica e Hardware'), ('programacao', 'Programação e Software')], default='eletronica', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
